apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-local
spec:
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app-container
          image: alonsoterrazas9/python-app@sha256:36a7cebb79385602da5c73f21e0608bf39ecbaa7687f6b86e42de8b9de866003
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
