apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app-container
          image: alonsoterrazas9/python-app@sha256:39e20f2d77acb22f369770db92ad2716c3dced63dcbabb5c4b72a40b8fd050e2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-credential
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-credential
                  key: password
