apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app-container
          image: alonsoterrazas9/python-app@sha256:f2b1259ee7fdae3885c70b9df937dc0a20cd281b1ed812caa693e4cc53064841
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
              # env:
          #  - name: DB_USER
          #   valueFrom:
          #    secretKeyRef:
#     name: my-app-credentials
#    key: username
#- name: DB_PASSWORD
# valueFrom:
#  secretKeyRef:
#   name: my-app-credentials
#  key: password
