{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "my-app-credentials",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "my-app-credentials",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgCJ1rstBxO7SftenZh6WUgYHZJVSHc7pw65QmZ9o1+b5RfM/jS73CRN+pGd/66ZTBw+hzoPi6mLgqOdlt+b310wo9kPkXpFVVzEpYdb34VL+aRh88VZB75TRJrLd4/0xDYFXKhKSqbppTRY1mxiVwaGDkT+wBlMg41Te46LPafqZhvO6UBk/usGwS6l83NqJYAw+dWRpkY9rymogz83OFlLuwTt1fJ5zTKQnoGtboKX3KOylcK7aJlSG2rGJ5k0KWe+yP9vJPT8SQCAxnwOIbbvDY7q2skSfgU0kJ9ydf6SLey6ALedbnkNgUF2gV1pR6dJscPsJzU0xBmYnwrKsDd6reKPppc9Avtn2bIPXXJecuk3fpgL9JEvSYUWvd5kYsJ3SFqHIUmI2BZ9Sf/bVw58ZOZgg2SMkcDaARONjq6b6biM3/ZCpLaQmo6qfTj3MFV0LbuU8HYAtqiiIumnPAY+IzxLCSIe/nL8ry/NuMiAqge0q7kl2ssNqKPehLc2AMDRVKj1yBdF7JI4j4HhZApqpIWDft8GmQ0kJ4aa2cegLcQBaHsGfACJDN04bW12FcGoEMwB8suAPnpInmHmdlaF0Ob0j63b6xD1+rRr3oB2k1KvENQhO7GMvAwxofNgfCM7C1TKCyMuHc8haWpd09FX0oGBfYvEOPMKscqQWvXp2LqKZDPbunPKFe//DqY6XXbYp2SPTiHfxMSGTISsnqZnLKJCG6tyEw==",
      "username": "AgAeWfwWSYAIoHVKq4BOHLDQO5sqUJsF+HQukWh54jjGuVwj2Q7m3+BwTkjDO2+Hvc8QGX+X3mc9B+9hUd1ZF4bOc/hTSHu1eF8jFRqSkqE8vEFeJP7ko8yNbYEa+Uu0HBSdQpMZn6BCpt+yf8sryRUvEfAnY+k/cx/W30qSi2rTpctCJM3/uXWxmI0WpSOdvFyvV91dv8p5+kDnY9eBd6Y/AcYJo8XYnDmi74xHarsCiXgGu22b/1891mNv0HXQwto+rGypAXc7tDZPoZjeiQ0Y0PQRVxAlQ/tDochthy3CdQqpCGSOidoZUfZP9AidOwBZye/D6bBwbF8OZUsGd9FEsJEm4gAnxuhneMIZTBY4fe41aq7MefoyN9UhlbJldaIujdrNpKICqNqB4+LjMs4rOKEbhKd5f2Dut9twd5dQxJ3JKXgUzzbBJmi8IpGpO/1QEq8dQZqO0n46we1ZsfgFT8EyjPOF/lhq8Cn3bjkXGYI2PTL02pGWTSpKnG+GsF/d01FnVUilbUcIzVQbc0h3TwwJSATrZchtJY4YTwF1HC3sxZH63ClpJheW8X3wmxsY3jwyLbPqAw7F/IP1dx3H6CduQ8H1AThcKs2/uzZiujRob7nz6sCQeK8n80GFe1NaucgRafJi1vca0c+LQKKoMe2TGUlKFcYCehxCl4RLy47xrTX2yL348lZJfZDn3uK2boWkiw=="
    }
  }
}
