{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "my-app-credentials",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "my-app-credentials",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "username": "AgA2S6QBFuoZtOZaghinH5eepODqjIcJXJVLTLrX8PrPEmh9Oiz+LKOccYrowpmsCkgXL7ABLwrMfgv9AAifZYwzrVoGn0JSUG+NscEDES5MQv4HHcvdXkeWuZjNo3f9FUSCCMRp9SXRGr1rLrgUPc93nxiHj/EVDd1MkmcywkscKme4WNn0aqTWDSOAkN7OJ0NGrYNbwtDKKyjXic9p/EnEwrs2gXaPzeffV6IxngM4IiPxmNGk+jqyBsZN0nFeVhfOuwxYeErAUbD5BpfbE3Zl9xrTGnMc1/JAKtzu7BBD1H0Z3rdh/Sla5xbTB5ZO61kT6QNCnUl2DFVckplZRCeSGeGf5qjog36qFFEJEK5zOpXjURYpvRgs266oWSxTwGbitbsdoYkhfcwRIk4P0JMt5PLBR+2TjRKs4y8TmmqdBkgyB31vlowpjpIwM1dttbe7Z0uiOrsLSOjtqQVw6LMP3fQpr9UT8GbMS5j93keuMfyxotNoXKwfVb/bv76AOaZ0hVbzRy77DJXsE4klpoTlmi4WF0cIBK16JAUKZqd2A/sUDhOEGnR4O5+vHjtnRftownnstvMB5a7JW6nz10gBxI09Z+KSd3G3RPx3+eHkuJU1FXpYMbIGjcoLIjXCNGvYk9bvMEcnLpf5PH6TpPZLt2ItlSXLjyJ7LU4OnRVwQkiG5jpY/Dn4+3MXd/igzKP2kXVZ7piBeAOiu6Y+H5B36c8+mg8t0m768KZOvyfEo25i4mWpXhvziemfz+tpSf7OeDx2xxoz+F2INZmLj6SeocF7iQOz6Q=="
    }
  }
}
